[manager]
cwd = { fg = "#94e2d5" }

preview_hovered = { fg = "#1e1e2e", bg = "#b4befe" }

find_keyword  = { fg = "#f9e2af", italic = true }
find_position = { fg = "#f5c2e7", bg = "reset", italic = true }

marker_copied   = { fg = "#a6e3a1", bg = "#a6e3a1" }
marker_cut      = { fg = "#f38ba8", bg = "#f38ba8" }
marker_marked   = { fg = "#94e2d5", bg = "#94e2d5" }
marker_selected = { fg = "#b4befe", bg = "#b4befe" }

tab_active   = { fg = "#1e1e2e", bg = "#cdd6f4" }
tab_inactive = { fg = "#cdd6f4", bg = "#45475a" }
tab_width    = 1

count_copied   = { fg = "#1e1e2e", bg = "#a6e3a1" }
count_cut      = { fg = "#1e1e2e", bg = "#f38ba8" }
count_selected = { fg = "#1e1e2e", bg = "#b4befe" }

border_symbol = "│"
border_style  = { fg = "#7f849c" }

syntect_theme = "~/.config/yazi/Catppuccin-mocha.tmTheme"

[mode]
normal_main = { fg = "#1e1e2e", bg = "#b4befe", bold = true }
normal_alt  = { fg = "#b4befe", bg = "#313244"}

select_main = { fg = "#1e1e2e", bg = "#a6e3a1", bold = true }
select_alt  = { fg = "#a6e3a1", bg = "#313244"}

unset_main  = { fg = "#1e1e2e", bg = "#f2cdcd", bold = true }
unset_alt   = { fg = "#f2cdcd", bg = "#313244"}

[status]
separator_open  = ""
separator_close = ""

progress_label  = { fg = "#ffffff", bold = true }
progress_normal = { fg = "#89b4fa", bg = "#45475a" }
progress_error  = { fg = "#f38ba8", bg = "#45475a" }

perm_type  = { fg = "#89b4fa" }
perm_read  = { fg = "#f9e2af" }
perm_write = { fg = "#f38ba8" }
perm_exec  = { fg = "#a6e3a1" }
perm_sep   = { fg = "#7f849c" }

[input]
border   = { fg = "#b4befe" }
title    = {}
value    = {}
selected = { reversed = true }

[confirm]
border     = { fg = "#b4befe" }
title      = { fg = "#b4befe" }
content    = {}
list       = {}
btn_yes    = { reversed = true }
btn_no     = {}

[completion]
border = { fg = "#b4befe" }

[tasks]
border  = { fg = "#b4befe" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#313244" }
cand            = { fg = "#94e2d5" }
rest            = { fg = "#9399b2" }
desc            = { fg = "#f5c2e7" }
separator       = "  "
separator_style = { fg = "#585b70" }
